<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lender;

class ZeroAprLendersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lenders = [
            [
                'name' => 'Wells Fargo Reflect',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '680-700+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 21,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Strong for long 0% strategies',
                'active' => true,
            ],
            [
                'name' => 'Citi Simplicity',
                'type' => 'bank',
                'bureau_pull' => 'Experian / Equifax',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 21,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'BT-focused, no late fees',
                'active' => true,
            ],
            [
                'name' => 'Citi Diamond Preferred',
                'type' => 'bank',
                'bureau_pull' => 'Experian / Equifax',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 21,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'BT-friendly',
                'active' => true,
            ],
            [
                'name' => 'Wells Fargo Active Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '670+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 670,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Cashback + easier approvals',
                'active' => true,
            ],
            [
                'name' => 'Wells Fargo Autograph',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '670+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 670,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Travel & lifestyle card',
                'active' => true,
            ],
            [
                'name' => 'Citi Double Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian / Equifax',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 18,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Strong BT option',
                'active' => true,
            ],
            [
                'name' => 'Citi Custom Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Category-based rewards',
                'active' => true,
            ],
            [
                'name' => 'Discover it Cash Back',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '660-680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 660,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 27.99,
                'income_sensitivity' => 'Low-Medium',
                'inquiry_sensitivity' => 'Low-Medium',
                'notes' => 'Rebuild-friendly',
                'active' => true,
            ],
            [
                'name' => 'Discover it Chrome',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '660+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 660,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 27.99,
                'income_sensitivity' => 'Low-Medium',
                'inquiry_sensitivity' => 'Low-Medium',
                'notes' => 'Lower barrier',
                'active' => true,
            ],
            [
                'name' => 'Chase Freedom Unlimited',
                'type' => 'bank',
                'bureau_pull' => 'Experian (varies)',
                'recommended_score' => '690+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 690,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'High',
                'notes' => '5/24 rule applies',
                'active' => true,
            ],
            [
                'name' => 'Chase Freedom Flex',
                'type' => 'bank',
                'bureau_pull' => 'Experian (varies)',
                'recommended_score' => '690+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 690,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'High',
                'notes' => '5/24 rule applies',
                'active' => true,
            ],
            [
                'name' => 'Chase Slate Edge',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 18,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'High',
                'notes' => 'BT-focused',
                'active' => true,
            ],
            [
                'name' => 'Capital One Quicksilver',
                'type' => 'bank',
                'bureau_pull' => 'All Three',
                'recommended_score' => '670+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 670,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium-High',
                'inquiry_sensitivity' => 'High',
                'notes' => 'Triple pull common',
                'active' => true,
            ],
            [
                'name' => 'Capital One SavorOne',
                'type' => 'bank',
                'bureau_pull' => 'All Three',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium-High',
                'inquiry_sensitivity' => 'High',
                'notes' => 'Triple pull common',
                'active' => true,
            ],
            [
                'name' => 'Chase Ink Cash (Business)',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '700+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 700,
                'max_credit_score' => 850,
                'intro_apr_months' => 12,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'High',
                'notes' => 'Business card, EIN-friendly',
                'active' => true,
            ],
            [
                'name' => 'Chase Ink Unlimited (Business)',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '700+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 700,
                'max_credit_score' => 850,
                'intro_apr_months' => 12,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'High',
                'notes' => 'Business card',
                'active' => true,
            ],
            [
                'name' => 'Amex Blue Business Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '680-700+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 12,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Low',
                'notes' => 'Soft pulls after relationship',
                'active' => true,
            ],
            [
                'name' => 'Navy Federal Platinum',
                'type' => 'credit_union',
                'bureau_pull' => 'TransUnion',
                'recommended_score' => '660+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 660,
                'max_credit_score' => 850,
                'intro_apr_months' => 12,
                'min_apr' => 0,
                'max_apr' => 18.00,
                'income_sensitivity' => 'Low-Medium',
                'inquiry_sensitivity' => 'Low',
                'notes' => 'Membership required',
                'active' => true,
            ],
            [
                'name' => 'U.S. Bank Visa Platinum',
                'type' => 'bank',
                'bureau_pull' => 'TransUnion (state-based)',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 18,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'State-sensitive pulls',
                'active' => true,
            ],
            [
                'name' => 'PNC Visa Platinum',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 680,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 24.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Regional bank',
                'active' => true,
            ],
            [
                'name' => 'Synchrony Premier Mastercard',
                'type' => 'bank',
                'bureau_pull' => 'TransUnion',
                'recommended_score' => '640-660+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 640,
                'max_credit_score' => 850,
                'intro_apr_months' => null,
                'min_apr' => 29.99,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Low',
                'inquiry_sensitivity' => 'Low',
                'notes' => 'Lower score approvals',
                'active' => true,
            ],
            [
                'name' => 'PayPal Cashback Mastercard',
                'type' => 'bank',
                'bureau_pull' => 'TransUnion',
                'recommended_score' => '660+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 660,
                'max_credit_score' => 850,
                'intro_apr_months' => 12,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Issued by Synchrony',
                'active' => true,
            ],
            [
                'name' => 'Bank of America Customized Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '670+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 670,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Strong national issuer',
                'active' => true,
            ],
            [
                'name' => 'Bank of America Unlimited Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian',
                'recommended_score' => '670+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 670,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Straightforward underwriting',
                'active' => true,
            ],
            [
                'name' => 'Truist Enjoy Cash',
                'type' => 'bank',
                'bureau_pull' => 'Experian / Equifax',
                'recommended_score' => '660-680+',
                'score_model' => 'FICO (primary)',
                'min_credit_score' => 660,
                'max_credit_score' => 850,
                'intro_apr_months' => 15,
                'min_apr' => 0,
                'max_apr' => 29.99,
                'income_sensitivity' => 'Medium',
                'inquiry_sensitivity' => 'Medium',
                'notes' => 'Regional variability',
                'active' => true,
            ],
        ];

        foreach ($lenders as $lenderData) {
            Lender::updateOrCreate(
                ['name' => $lenderData['name']], // Match by name
                $lenderData
            );
        }

        $this->command->info('✅ 0% APR Lenders seeded successfully!');
    }
}
